/*
 * generated by Xtext 2.16.0
 */
package io.exatn.theia.edl.ide

import io.exatn.theia.edl.ide.server.codeActions.TensorsCodeActionService
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2

/**
 * Use this class to register ide components.
 */
class TensorsIdeModule extends AbstractTensorsIdeModule {
	
	def Class<? extends ICodeActionService2> bindICodeActionService2() {
		TensorsCodeActionService
	}
}
