/*
 * generated by Xtext 2.16.0
 */
package io.exatn.theia.edl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TensorsRuntimeModule extends AbstractTensorsRuntimeModule {
}
