/*
 * generated by Xtext 2.16.0
 */
package io.exatn.theia.edl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TensorsStandaloneSetup extends TensorsStandaloneSetupGenerated {

	def static void doSetup() {
		new TensorsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
