/*
 * generated by Xtext 2.16.0
 */
package io.exatn.theia.edl.tests

import com.google.inject.Inject
import io.exatn.theia.edl.Tensors.TensorDiagram
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(TensorsInjectorProvider)
class TensorsParsingTest {
	@Inject
	ParseHelper<TensorDiagram> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			tensorTensorDiagram MrsGrantsSecretCompartments
			
			dimension doorClosed
			dimension drawOpened
			dimension lightOn
			dimension panelClosed
			
			tensor active
				lightOn	=> waitingForDraw
				drawOpened => waitingForLight
			
			tensor idle
				doorClosed => active
			
			tensor waitingForLight 
				lightOn => idle
			
			tensor waitingForDraw
				drawOpened => unlockedPanel
			
			tensor unlockedPanel
				panelClosed => idle
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
